# Generated by Django 5.2.4 on 2025-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='成本单价'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_cost_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='成本总金额'),
        ),
    ]
