# Generated by Django 5.2.4 on 2025-08-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_cost_price_sale_total_cost_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_enterprise_l3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='企业-小分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_enterprise_l4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='企业-细分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_standard_l3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标准-小分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_standard_l4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标准-细分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketing_authorization_holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='上市许可持有人'),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品本位码'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='生产企业'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='单位'),
        ),
    ]
