# Generated by Django 5.2.4 on 2025-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_category_enterprise_l3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='负责人'),
        ),
    ]
