# Generated by Django 5.2.4 on 2025-08-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_responsible_person'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('enterprise', 'employee_number')},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('enterprise', 'supplier_code')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_standard_l1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_standard_l2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_standard_l3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_standard_l4',
        ),
        migrations.AddField(
            model_name='employee',
            name='source_employee_id',
            field=models.CharField(default=1, max_length=100, verbose_name='源系统职员ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='batch_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='批次号'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='member',
            name='source_member_id',
            field=models.CharField(default=1, max_length=100, verbose_name='源系统会员ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='document_number',
            field=models.CharField(default=1, max_length=100, verbose_name='单据编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='batch_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='批次号'),
        ),
        migrations.AddField(
            model_name='sale',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='有效期'),
        ),
        migrations.AddField(
            model_name='sale',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='sale',
            name='source_sale_detail_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='源系统销售明细ID'),
        ),
        migrations.AddField(
            model_name='sale',
            name='source_sale_id',
            field=models.CharField(default=1, max_length=100, verbose_name='源系统销售单据ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='source_store_id',
            field=models.CharField(default=1, max_length=100, verbose_name='源系统门店ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_code',
            field=models.CharField(default=1, max_length=100, verbose_name='门店编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='source_supplier_id',
            field=models.CharField(default=1, max_length=100, verbose_name='源系统供应商ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='member',
            name='total_consumption',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='累计消费金额'),
        ),
        migrations.AlterField(
            model_name='product',
            name='member_price',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='会员价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='零售价'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='actual_price',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='实收单价'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='成本单价'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='折扣总金额'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='list_price',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='应收单价'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='实收总金额'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_cost_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='成本总金额'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('enterprise', 'employee_number'), ('enterprise', 'source_employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('enterprise', 'source_member_id')},
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('enterprise', 'source_store_id')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('enterprise', 'source_supplier_id'), ('enterprise', 'supplier_code')},
        ),
    ]
