# Generated by Django 5.2.4 on 2025-08-06 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_employee_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='issuing_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store', verbose_name='办卡门店'),
        ),
    ]
