# Generated by Django 5.2.4 on 2025-08-06 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_member_issuing_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='gross_profit_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='毛利额'),
        ),
        migrations.CreateModel(
            name='EnterpriseAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.enterprise', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '企业API密钥',
                'verbose_name_plural': '企业API密钥',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
