# Generated by Django 5.2.4 on 2025-08-07 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sale_gross_profit_amount_enterpriseapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.enterprise', verbose_name='所属企业'),
        ),
    ]
