# Generated by Django 5.2.4 on 2025-08-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_enterprise'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorysnapshot',
            unique_together={('enterprise', 'product', 'store', 'batch_number', 'snapshot_date')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('enterprise', 'document_number', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('enterprise', 'source_sale_id', 'source_sale_detail_id')},
        ),
    ]
