# Generated by Django 5.2.4 on 2025-08-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_inventorysnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='purchase',
            name='batch_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='批次号'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='source_purchase_id',
            field=models.CharField(default=1, max_length=100, verbose_name='源系统采购单据ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('enterprise', 'source_purchase_id', 'product')},
        ),
    ]
