# Generated by Django 5.2.4 on 2025-08-12 01:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_purchase_unique_together_purchase_batch_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_l1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='大分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_l2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='中分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_l3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='小分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_l4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='细分类'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enterprise', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '会员标签',
                'verbose_name_plural': '会员标签',
                'unique_together': {('enterprise', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.membertag', verbose_name='标签'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
