# Generated by Django 5.2.4 on 2025-08-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_category_l1_product_category_l2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTenantDefaultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('provider_key', models.CharField(choices=[('gpt5', 'GPT-5'), ('gemini', 'Gemini'), ('deepseek', 'DeepSeek'), ('zhipu', 'Zhipu'), ('mock', 'Mock')], max_length=32)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_tenant_default_model',
            },
        ),
        migrations.CreateModel(
            name='AiModelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('provider_key', models.CharField(choices=[('gpt5', 'GPT-5'), ('gemini', 'Gemini'), ('deepseek', 'DeepSeek'), ('zhipu', 'Zhipu'), ('mock', 'Mock')], max_length=32)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_model_preference',
                'indexes': [models.Index(fields=['tenant_id', 'user_id'], name='ai_model_pr_tenant__2a9c59_idx')],
                'unique_together': {('tenant_id', 'user_id')},
            },
        ),
    ]
