# Generated by Django 5.2.4 on 2025-08-13 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aitenantdefaultmodel_aimodelpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTenantTokenAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('plan', models.CharField(default='basic', max_length=64)),
                ('token_balance', models.BigIntegerField(default=0)),
                ('soft_limit', models.BigIntegerField(default=0)),
                ('hard_limit', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_tenant_token_account',
            },
        ),
        migrations.CreateModel(
            name='AiChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('agent', models.CharField(default='default', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_chat_session',
                'indexes': [models.Index(fields=['tenant_id', 'agent', 'updated_at'], name='ai_chat_ses_tenant__0e8413_idx')],
            },
        ),
        migrations.CreateModel(
            name='AiRagDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='多租户隔离标识', max_length=64)),
                ('source', models.CharField(default='api', help_text='来源（api/upload/crawl/...）', max_length=64)),
                ('title', models.CharField(blank=True, default='', help_text='标题或摘要', max_length=255)),
                ('tags', models.CharField(blank=True, default='', help_text='逗号分隔标签', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='自定义元数据')),
                ('status', models.CharField(default='ready', help_text='状态：ready/disabled', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_rag_document',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='ai_rag_docu_tenant__07bff9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AiRagChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(default=0, help_text='在原文档中的顺序（从0开始）')),
                ('content', models.TextField(help_text='分块后的纯文本内容')),
                ('token_count', models.IntegerField(default=0, help_text='估算 token 数（用于限额与调优）')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.airagdocument')),
            ],
            options={
                'db_table': 'ai_rag_chunk',
            },
        ),
        migrations.CreateModel(
            name='AiRagEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(help_text='向量提供商，如 local/gpt/zhipu', max_length=32)),
                ('model', models.CharField(help_text='具体向量模型名', max_length=64)),
                ('dim', models.IntegerField(help_text='向量维度')),
                ('vector', models.JSONField(help_text='浮点数组（长度等于 dim）')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='core.airagchunk')),
            ],
            options={
                'db_table': 'ai_rag_embedding',
            },
        ),
        migrations.CreateModel(
            name='AiRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('agent', models.CharField(max_length=64)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('latency_ms', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aichatsession')),
            ],
            options={
                'db_table': 'ai_run',
            },
        ),
        migrations.CreateModel(
            name='AiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='core.airun')),
            ],
            options={
                'db_table': 'ai_call_log',
            },
        ),
        migrations.CreateModel(
            name='AiTokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('change', models.BigIntegerField()),
                ('reason', models.CharField(default='usage', max_length=128)),
                ('related_run_id', models.CharField(blank=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_token_transaction',
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='ai_token_tr_tenant__33a6cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AiMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.aichatsession')),
            ],
            options={
                'db_table': 'ai_message',
                'indexes': [models.Index(fields=['session', 'created_at'], name='ai_message_session_3a11aa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='airagchunk',
            index=models.Index(fields=['document', 'ordinal'], name='ai_rag_chun_documen_e10863_idx'),
        ),
        migrations.AddIndex(
            model_name='airagembedding',
            index=models.Index(fields=['chunk', 'provider_key', 'model'], name='ai_rag_embe_chunk_i_825e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['tenant_id', 'created_at'], name='ai_run_tenant__0d20e7_idx'),
        ),
        migrations.AddIndex(
            model_name='aicalllog',
            index=models.Index(fields=['model', 'created_at'], name='ai_call_log_model_937f6a_idx'),
        ),
    ]
