# Generated by Django 5.2.4 on 2025-08-13 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aitenanttokenaccount_aichatsession_airagdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsAlertChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(help_text='email|webhook', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_ops_alert_channel',
                'indexes': [models.Index(fields=['tenant_id', 'kind', 'is_active'], name='ai_ops_aler_tenant__e39acf_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='多租户隔离标识', max_length=64)),
                ('name', models.CharField(help_text='规则名称', max_length=128)),
                ('type', models.CharField(help_text='规则类型：sales_drop/stockout/price_spike', max_length=32)),
                ('config', models.JSONField(blank=True, default=dict, help_text='规则参数 JSON')),
                ('is_active', models.BooleanField(default=True, help_text='启用/停用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_ops_alert_rule',
                'indexes': [models.Index(fields=['tenant_id', 'is_active', 'type'], name='ai_ops_aler_tenant__d93d35_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('key', models.CharField(db_index=True, max_length=256)),
                ('severity', models.CharField(default='medium', max_length=16)),
                ('status', models.CharField(default='open', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('hit_count', models.IntegerField(default=1)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.opsalertrule')),
            ],
            options={
                'db_table': 'ai_ops_incident',
                'indexes': [models.Index(fields=['tenant_id', 'status', 'severity', 'last_seen'], name='ai_ops_inci_tenant__74ed23_idx'), models.Index(fields=['tenant_id', 'key'], name='ai_ops_inci_tenant__3c5e02_idx')],
            },
        ),
    ]
