from django.urls import path
from .views import (
    # UI Views
    StoreListView,
    StoreDetailView,
    ProductListView,
    ProductCreateView,
    ProductDetailView,
    ProductUploadView,
    SaleCreateView,
    UserInfoView,
    StoreKPIProgressView,
    SupplierListView,
    SupplierCreateView,
    SupplierDetailView,
    PurchaseListView,
    PurchaseCreateView,
    PurchaseDetailView,
    MemberListView,
    MemberCreateView,
    MemberDetailView,
    EmployeeListView,
    EmployeeCreateView,
    EmployeeDetailView,
    TagListView,
    TagCreateView,
    TagDetailView,
    # Sync Views
    ProductBatchSyncView,
    StoreBatchSyncView,
    SupplierBatchSyncView,
    PurchaseBatchSyncView,
    SaleBatchSyncView,
    InventorySnapshotBatchSyncView,
    MemberBatchSyncView,
    EmployeeBatchSyncView,
    # AI Views
    AIAutoCategorizeView,
)

urlpatterns = [
    # --- 面向前端UI的API ---
    path('user/info/', UserInfoView.as_view(), name='user-info'),
    path('home/kpi-progress/', StoreKPIProgressView.as_view(), name='home-kpi-progress'),
    path('stores/', StoreListView.as_view(), name='store-list'),
    path('stores/<int:pk>/', StoreDetailView.as_view(), name='store-detail'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/create/', ProductCreateView.as_view(), name='product-create'),
    path('products/upload/', ProductUploadView.as_view(), name='product-upload'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('sales/create/', SaleCreateView.as_view(), name='sale-create'),
    path('suppliers/', SupplierListView.as_view(), name='supplier-list'),
    path('suppliers/create/', SupplierCreateView.as_view(), name='supplier-create'),
    path('suppliers/<int:pk>/', SupplierDetailView.as_view(), name='supplier-detail'),
    path('purchases/', PurchaseListView.as_view(), name='purchase-list'),
    path('purchases/create/', PurchaseCreateView.as_view(), name='purchase-create'),
    path('purchases/<int:pk>/', PurchaseDetailView.as_view(), name='purchase-detail'),
    path('members/', MemberListView.as_view(), name='member-list'),
    path('members/create/', MemberCreateView.as_view(), name='member-create'),
    path('members/<int:pk>/', MemberDetailView.as_view(), name='member-detail'),
    path('employees/', EmployeeListView.as_view(), name='employee-list'),
    path('employees/create/', EmployeeCreateView.as_view(), name='employee-create'),
    path('employees/<int:pk>/', EmployeeDetailView.as_view(), name='employee-detail'),
    path('tags/', TagListView.as_view(), name='tag-list'),
    path('tags/create/', TagCreateView.as_view(), name='tag-create'),
    path('tags/<int:pk>/', TagDetailView.as_view(), name='tag-detail'),

    # --- 数据连接器专用API端点 ---
    path('data/products/sync/', ProductBatchSyncView.as_view(), name='data-product-sync'),
    path('data/stores/sync/', StoreBatchSyncView.as_view(), name='data-store-sync'),
    path('data/suppliers/sync/', SupplierBatchSyncView.as_view(), name='data-supplier-sync'),
    path('data/purchases/sync/', PurchaseBatchSyncView.as_view(), name='data-purchase-sync'),
    path('data/sales/sync/', SaleBatchSyncView.as_view(), name='data-sale-sync'),
    path('data/inventory/sync/', InventorySnapshotBatchSyncView.as_view(), name='data-inventory-sync'),
    path('data/members/sync/', MemberBatchSyncView.as_view(), name='data-member-sync'),
    path('data/employees/sync/', EmployeeBatchSyncView.as_view(), name='data-employee-sync'),

    # --- AI功能API端点 ---
    path('ai/products/auto-categorize/', AIAutoCategorizeView.as_view(), name='ai-product-auto-categorize'),
]
